#msggw config
msggw:
  type: ws #ws websocket | mqtt
  port: 9000

admin_api:
  port: 9001

chat_api:
  port: 9002

redis:
  ip: 101.33.251.102
  port: 16379

dbs:
  ip: 127.0.0.1
  port: 9003

mysql:
  ip: 101.33.251.102
  port: 13306
  passwd: openIM123
  database: tuiyun_chat